name = "screaming-snake-case-do"
route = { pattern = "screaming.snake.case/*", zone_name = "case.do" }
main = "worker.js"
usage_model = "unbound"
compatibility_date = "2022-09-23"
logpush = true

services = [
  { binding = "CTX", service = "ctx-do", environment = "production" }
]
